# Site settings
title: Roller Derby News
email: rollerderbynewsitalia@gmail.com
description: "Streaming service for your roller derby bouts. Real time score updates and rankings too! Follow your team here!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ridonato
  - title: facebook
    url: https://www.facebook.com/rollerderbynews
  - title: stack-overflow
    url: http://stackoverflow.com/users/664567/rdonato
  - title: bitbucket 
    url: https://bitbucket.org/rdonato
  - title: github
    url: https://github.com/rdonato

# Postal address (add as many lines as necessary)
address:
  - line: via Monza 11
  - line:  20030 Senago (MI)

# Build settings
markdown: kramdown
permalink: pretty
